//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace VfpEntityFrameworkProvider.Tests
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DecimalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DecimalEntities object using the connection string found in the 'DecimalEntities' section of the application configuration file.
        /// </summary>
        public DecimalEntities() : base("name=DecimalEntities", "DecimalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DecimalEntities object.
        /// </summary>
        public DecimalEntities(string connectionString) : base(connectionString, "DecimalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DecimalEntities object.
        /// </summary>
        public DecimalEntities(EntityConnection connection) : base(connection, "DecimalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Decimaltable> Decimaltables
        {
            get
            {
                if ((_Decimaltables == null))
                {
                    _Decimaltables = base.CreateObjectSet<Decimaltable>("Decimaltables");
                }
                return _Decimaltables;
            }
        }
        private ObjectSet<Decimaltable> _Decimaltables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Decimaltables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecimaltables(Decimaltable decimaltable)
        {
            base.AddObject("Decimaltables", decimaltable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DecimalModel", Name="Decimaltable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Decimaltable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Decimaltable object.
        /// </summary>
        /// <param name="ipk">Initial value of the Ipk property.</param>
        /// <param name="ivalue">Initial value of the Ivalue property.</param>
        public static Decimaltable CreateDecimaltable(global::System.Int32 ipk, global::System.Decimal ivalue)
        {
            Decimaltable decimaltable = new Decimaltable();
            decimaltable.Ipk = ipk;
            decimaltable.Ivalue = ivalue;
            return decimaltable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ipk
        {
            get
            {
                return _Ipk;
            }
            set
            {
                if (_Ipk != value)
                {
                    OnIpkChanging(value);
                    ReportPropertyChanging("Ipk");
                    _Ipk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ipk");
                    OnIpkChanged();
                }
            }
        }
        private global::System.Int32 _Ipk;
        partial void OnIpkChanging(global::System.Int32 value);
        partial void OnIpkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Ivalue
        {
            get
            {
                return _Ivalue;
            }
            set
            {
                OnIvalueChanging(value);
                ReportPropertyChanging("Ivalue");
                _Ivalue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ivalue");
                OnIvalueChanged();
            }
        }
        private global::System.Decimal _Ivalue;
        partial void OnIvalueChanging(global::System.Decimal value);
        partial void OnIvalueChanged();

        #endregion

    
    }

    #endregion

    
}
