//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfpEntityFrameworkProvider.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VfpEntityFrameworkProvider.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DecimalTable {
            get {
                object obj = ResourceManager.GetObject("DecimalTable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FreeTables {
            get {
                object obj = ResourceManager.GetObject("FreeTables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Schema Namespace=&quot;NorthwindEFModel&quot; Alias=&quot;Self&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2008/09/edm&quot;&gt;
        ///
        ///  &lt;!-- Model Defined Function (MDF) --&gt;
        ///  &lt;Function Name=&quot;TimesMDF&quot; ReturnType=&quot;Int32&quot;&gt;
        ///    &lt;Parameter Name=&quot;X&quot; Type=&quot;Int32&quot; /&gt;
        ///    &lt;Parameter Name=&quot;Y&quot; Type=&quot;Int32&quot; /&gt;
        ///    &lt;DefiningExpression&gt;X * Y&lt;/DefiningExpression&gt;
        ///  &lt;/Function&gt;
        ///
        ///  &lt;!-- MDF that returns a collection of entities--&gt;
        ///  &lt;Function Name=&quot;GetProductsForCategory&quot; ReturnType=&quot;Collection(Northw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindEFModelCsdl {
            get {
                return ResourceManager.GetString("NorthwindEFModelCsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Mapping Space=&quot;C-S&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2008/09/mapping/cs&quot;&gt;
        ///  &lt;EntityContainerMapping
        ///    StorageEntityContainer=&quot;dbo&quot;
        ///    CdmEntityContainer=&quot;NorthwindEntities&quot;&gt;
        ///
        ///    &lt;EntitySetMapping Name=&quot;Orders&quot;&gt;
        ///      &lt;!-- 
        ///      The IsTypeOf keyword tells the mapping that the following mapping applies to all subtypes of 
        ///      the given Type (in this case, InternationalOrder as well as Order)
        ///      --&gt;
        ///      &lt;EntityTypeMapping TypeName=&quot;IsTypeOf( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindEFModelMsl {
            get {
                return ResourceManager.GetString("NorthwindEFModelMsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Schema Namespace=&quot;NorthwindEFModel.Store&quot;
        ///        Alias=&quot;Self&quot;
        ///        xmlns=&quot;http://schemas.microsoft.com/ado/2009/02/edm/ssdl&quot;
        ///        Provider=&quot;VfpEntityFrameworkProvider&quot;
        ///        ProviderManifestToken=&quot;VFP9&quot;&gt;
        ///  &lt;EntityContainer Name=&quot;dbo&quot;&gt;
        ///    &lt;EntitySet Name=&quot;Employees&quot;
        ///               EntityType=&quot;NorthwindEFModel.Store.Employees&quot; /&gt;
        ///    &lt;EntitySet Name=&quot;Regions&quot;
        ///               EntityType=&quot;NorthwindEFModel.Store.Regions&quot; /&gt;
        ///    &lt;EntitySet Name=&quot;Customer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindEFModelSsdl {
            get {
                return ResourceManager.GetString("NorthwindEFModelSsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NorthwindVfp {
            get {
                object obj = ResourceManager.GetObject("NorthwindVfp", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
